-- MySQL Script generated by MySQL Workbench
-- Sun 28 Aug 2022 10:57:34 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca` ;
USE `biblioteca` ;

-- -----------------------------------------------------
-- Table `biblioteca`.`TelefoneCliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`TelefoneCliente` (
  `idTelefoneCliente` INT NOT NULL,
  `numerotelefone` INT NOT NULL,
  PRIMARY KEY (`idTelefoneCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`Status_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Status_pedido` (
  `idStatus_pedido` INT NOT NULL,
  `Preparando` INT NOT NULL,
  `Em_entrega` INT NOT NULL,
  `Entregue` INT NOT NULL,
  PRIMARY KEY (`idStatus_pedido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Pedido` (
  `idPedido` INT NOT NULL,
  `data_emissao` INT NOT NULL,
  `Status_pedido_idStatus_pedido` INT NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_Pedido_Status_pedido1_idx` (`Status_pedido_idStatus_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Status_pedido1`
    FOREIGN KEY (`Status_pedido_idStatus_pedido`)
    REFERENCES `biblioteca`.`Status_pedido` (`idStatus_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Cliente` (
  `Nomedocliente` VARCHAR(45) NOT NULL,
  `RG` INT NOT NULL,
  `Endereço_rua` VARCHAR(45) CHARACTER SET 'ascii' NOT NULL COMMENT '\n',
  `Endereco_numero` INT NOT NULL,
  `Endereco_bairro` VARCHAR(45) NOT NULL,
  `TelefoneCliente_idTelefoneCliente` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  PRIMARY KEY (`Nomedocliente`, `Endereço_rua`),
  INDEX `fk_Cliente_TelefoneCliente_idx` (`TelefoneCliente_idTelefoneCliente` ASC) VISIBLE,
  INDEX `fk_Cliente_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_TelefoneCliente`
    FOREIGN KEY (`TelefoneCliente_idTelefoneCliente`)
    REFERENCES `biblioteca`.`TelefoneCliente` (`idTelefoneCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `biblioteca`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`TelefoneEntregador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`TelefoneEntregador` (
  `idTel_Entregador` INT NOT NULL,
  `TelefoneEntregador` INT NOT NULL,
  PRIMARY KEY (`idTel_Entregador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`Entregador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Entregador` (
  `idEntregador` INT NOT NULL,
  `NomedoEntregador` VARCHAR(45) NOT NULL,
  `TelefoneEntregador_idTel_Entregador` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  PRIMARY KEY (`idEntregador`),
  INDEX `fk_Entregador_TelefoneEntregador1_idx` (`TelefoneEntregador_idTel_Entregador` ASC) VISIBLE,
  INDEX `fk_Entregador_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  CONSTRAINT `fk_Entregador_TelefoneEntregador1`
    FOREIGN KEY (`TelefoneEntregador_idTel_Entregador`)
    REFERENCES `biblioteca`.`TelefoneEntregador` (`idTel_Entregador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Entregador_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `biblioteca`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
